### ISSUE TITLE
Hyde doesn't accept lists as context providers

### ISSUE THREAD

**Issue by F30** [hyde/hyde#189]
When using an external file as context provider, Hyde expects the top-level structure of that one to be an associative array (YAML equivalent of a Python dictionary). If it is a list instead, it will just get ignored.
#### Example

``` yaml
# site.yaml
context:
    providers:
        example: example.yaml
```

``` yaml
# example.yaml
- Foo
- Bar
```

``` jinja
{# demo.html #}
<ul>
    {% for element in example %}
    <li>{{ element }}</li>
    {% endfor %}
</ul>
```

A possible workaround is to add an associative array at the top-level of the data file and the list below that. But in my opintion, there's nothing wrong with having a data structure as shown above.

It even works when the list is not used as a context provider, but directly put into _sites.yaml_ as `data` like this:

``` yaml
# site.yaml
context:
    data:
        example:
            - Foo
            - Bar
```
