### ISSUE TITLE
could not publish to github: page build failed

### ISSUE THREAD

**Issue by ghost** [hyde/hyde#238]
I follow the guide. and use the development version.

```
hyde create
hyde gen
```

then I modify the site.yaml, and add 

```
publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../lixiangalwh.github.com
        url: git@github.com:lixiangalwh/lixiangalwh.github.com.git
```

finally, I run

```
hyde publish -p github
```

everything seems ok.  however, I can't open my site.  and the project settings show the error message:

```
Your page is having problems building: page build failed
```

could I get some help here?

---

I tried and find a solution.

use "hyde gen" in other folder and publish it into the repo folder.

I don't find documentation anywhere, though.

But since it's solved, I'll close the issue.
